title: "penguincoco"
author: ""
description: "just a girl that likes to draw and write."

# Jekyll settings
permalink: /:title/          # see https://jekyllrb.com/docs/permalinks/
paginate: 10                  # number of articles per page, remove to disable pagination
excerpt_separator: "\n\n\n"  # indicates the end of the excerpt by two blank lines

# Page settings
show_excerpts: true          # show article previews on the home page instead of headlines
hide_title: false            # remove site heading in the header
post_footer: true            # show previous and next links at the end of each post
date_format: "%B %d, %Y"     # see http://shopify.github.io/liquid/filters/date/

# Theme settings
style: default               # choose between "default", "contrast" and "minimal"
dark_theme: false            # enables dark mode

navigation:                  # (optional) site navigation in the header
  - index.html
  - writings.md
  - artwork.md
  - iconProjects.md

icons:                       # (optional) icons in the header, see http://fontawesome.com/icons
  envelope: "mailto:samantha.s.chuang@gmail.com"
  instagram: "https://www.instagram.com/penguincoco/"
  etsy: "https://www.etsy.com/shop/penguincucco/"
  twitch: "https://www.twitch.tv/penguincoco"
  itch-io: "https://itch.io/profile/penguincoco"
  youtube: "https://www.youtube.com/channel/UC5wE9w5h7eawYhbzmW2Ip9g"

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

remote_theme: niklasbuschmann/contrast

plugins: 
 - jekyll-remote-theme
 - jekyll-feed
 - jekyll-paginate
 - jekyll-default-layout
